project:
  type: website
  output-dir: docs

website:
  title: "necessitous"
  navbar:
    right:
      - about.qmd
      - icon: mastodon
        href: https://mastodon.social/%40rauchway
format:
  html:
    theme: flatly
    css: styles.css



