project:
  type: website
  output-dir: docs

website:
  title: "necessitous"
  site-url: https://erauchway.github.io
  description: "A blog full of pedantry about the era of the Roosevelt administration, 1933--1945"
  navbar:
    right:
      - about.qmd
      - icon: mastodon
        href: https://mastodon.social/%40rauchway
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css



