---
title: Architecture after a Green New Deal, UCLA
date: 2023-11-10
categories:
    - New Deal
    - Public works
    - Green New Deal
    - TVA
---

Here are my slides from my presentation at the rather wonderful conference, ["Architecture after a Green New Deal,"](https://www.aud.ucla.edu/news-events/events/fall2023-aagnd-conference) at the UCLA Department of Architecture and Urban Design. 

:::: {.columns .v-center-container}

::: {.column width="50%"}
<iframe height="480" width="640" src="https://erauchway.github.io/present/gnd_ucla.html">
</iframe>
:::

::: {.column width="50%"}

:::

::::



My assignment was to talk a bit about the o.g. New Deal, so I took the opportunity to talk about how the Roosevelt administration used public works programs for political and ideological ends. That is, Roosevelt's concept of a sample publicly owned facility as a "yardstick," to determine fair pricing and operating procedures, was ideological; the use of a sufficiently large public works program to influence labor standards, wage practices, and the legitimacy of unions was an ideological purpose; Roosevelt's own statement that direct employment would "help restore the close relationship with the people which is necessary to preserve our democratic form of government" was ideological, reflecting his view that public works programs could help to reverse the alienation endemic to the modern condition.[@rauchwayWhyNewDeal2021, 32]

Moreover, the ubiquity of public works designed to foster community and edifying leisure pursuits constituted an ideological commitment to establish a right to the good life for everyone, regardless of station.

All of that constituted an imperative to design for democracy, more or less; I also discussed the way that the TVA in particular exemplified an imperative to design for sustainability.

You can see some of the visuals I assembled to argue the case on the slides.
