---
title: "Fearless finger"
author: "Eric Rauchway"
date: 2023-04-24
categories:
    - La Guardia
    - Civilian Defense
---

Fiorello La Guardia, Federal Director of the Office of Civilian Defense and candidate for a third term as mayor of New York City on a Fusion ticket, in a photograph used in the *Saturday Evening Post* of September 6, 1941.

![One of seven evocative portraits of La Guardia featured on the first page of "Fearless Fiorello" by William R. Conklin; this version is from an ad for the article that appeared in *Time,* because in the bound version of the *Saturday Evening Post* the photograph is too close to the gutter to be reproduced intact.](IMG_5672.JPG)

The article begins with a La Guardia-ism many people will know, but perhaps without the context. In February 1941, appearing before the Senate Foreign Relations Committee to testify in favor of Lend-Lease, La Guardia was asked about earlier remarks by Justice Herbert O'Brien of the Queens Domestic Relations Court, who told the committee that passing Lend-Lease would lead to racial conflict. One of the senators reminded the Little Flower he had appointed O'Brien. The mayor replied, "Senator . . . I have made a lot of good appointments, and I think I'm pretty good. But when I make a mistake---it's a beaut!"[@conklinFearlessFiorello1941a, 12]

The article does not give context for the wordless remark depicted in the photograph.
