---
title: Andrew Hickey, practitioner of old-school American Studies (laudatory)
author: Eric Rauchway
date: 2025-04-13
draft: FALSE
categories: 
  - Historiography
  - American Studies
---

Even though I am not old enough to have encountered the mid-century American Studies scholars when they were flourishing or in many cases, when they were even still alive, the books that brought me into my own career in US history belong to that tradition: *American Humor,* by Constance Rourke, or *Love and Death in the American Novel,* by Leslie Fiedler, say. This work is not necessarily *right,*  per se, but it is certainly thought-provoking and inasmuch as that is the point of scholarship, *good.*[^1] In most cases it tells you things you didn't already know and maybe more important it works by making connections which wouldn't have occurred to a reader not as deeply steeped in the sources as the writer---which is essentially every reader.

Andrew Hickey does the podcast, "A History of Rock Music in 500 Songs," which you have probably already had recommended to you but maybe not because it plainly belongs to that tradition, into which we could also throw Richard Hofstadter, David M. Potter, John Hope Franklin, and some of the other cast of characters from [Nick Witham's recent scholarship.](https://press.uchicago.edu/ucp/books/book/chicago/P/bo196664682.html) 

Hickey is an admirable cultural historian in part because he lets you know how he [works:](https://500songs.com/podcast/song-177-never-learn-not-to-love-by-the-beach-boys-part-one/#more-2348)

>connections are *everywhere*. We only see them when we’re looking for them. And they only have the meaning that we impose. Now, this happens to be a big chunk of the way I tell stories — and indeed it’s an important part of the way *anyone* tells stories. You look for patterns and connections that other people haven’t seen before, and present them to the audience. Sometimes those patterns have actual meaning that sheds light on the history, other times they’re just interesting resonances and coincidences that make for an interesting story.

He also revises himself in light of what he finds to be [persuasive evidence:](https://500songs.com/2024/12/10/next-episode-coming-soon/)

>when checking a minor detail I discovered a book published this year, after I’d bought the books I used for the research, which showed that everything in the first half of the episode---everything that had been published in every book on Huddie Ledbetter, who is the focus of that first half---was badly mistaken. I had to totally scrap a completed script and redo the research from scratch. 

And he has wonderful, no-nonsense [asides:](https://500songs.com/podcast/song-177-never-learn-not-to-love-by-the-beach-boys-part-3-mister-can-you-give-me-some-direction/#more-2421)

>[John] Lomax was born in Mississippi in 1867, two years after the ending of the Slaveholders’ Rebellion (later euphemised as the American Civil War)

The podcast is a delight; I gather there is also now [a book.](https://books2read.com/u/mVrzYM) 

[^1]: I think much of it is also wrong, but in interesting ways, because it addresses interesting questions, and therefore merits engagement.