---
title: "What this country needs"
author: "Eric Rauchway"
date: "2025-10-25"
categories:
  - Hoover
  - Historiography
---

Herbert Hoover problem was *not* that he was a technocrat who didn't understand politics. He was a savvy political operator and a master of public relations who understood that it was to his advantage to *seem* like a technocrat who didn't understand politics. So when you say he was a technocrat who didn't understand politics, you are falling for a hustle, in the manner of someone who perceives Fast Eddie Felson isn't striking the balls quite so smartly as you had heard.

James MacLafferty, one of Hoover's aides and fixers, kept a diary and in the entry for April 14, 1932, he wrote about what he called a "morning after" scene in the Cabinet room of the White House.


> Cigarette and cigar ends were crowding ash trays to their full capacity, empty cigarette packages were on the cabinet table and on the floor as were also wadded pieces of paper on which memorandums had been made. On the floor, by the President's chair, were four paper bands that had once been around cigars the President had smoked. I recognized them at once and I picked them up determined that I would make them a part of this history.

MacLafferty pasted a couple of Hoover's cigar bands into his diary. (Because he kept the diary in duplicate, there are two in each copy. One's in the Herbert Hoover Presidential Library in West Branch, Iowa, and the other is in the Hoover Institution Archives in Stanford, California.)

MacLafferty was commemorating one of Hoover's successful lobbying efforts: the President had cajoled Congress into [cutting federal salaries as a Depression-fighting measure.](https://hoover.blogs.archives.gov/2020/07/29/the-economy-act-of-1932/)

Now you can say this episode shows that Hoover had terrible instincts, so far as macroeconomic policy goes, but I wouldn't say it shows he didn't know how to do politicking. He was able by dint of traditional jawboning and soft-selling to get his bad ideas through a Democratic House majority. He was a very good politician---which doesn't by any stretch mean he had good policies.