---
title: "The great essayist, or as I like to call him, 'Babe'"
author: "Eric Rauchway"
date: "2025-10-27"
categories:
  - New Deal
---

Running for reelection in 1936, Franklin Roosevelt emphasized that the New Deal had averted revolution. He referred to the threat of communism, but I don't believe he had ever really believed communism was in the offing; what he really feared in 1933 was dictatorship.

In the course of defending democracy, he argued, the New Deal had achieved the highest form of conservatism.

> Never has a Nation made greater strides in the safeguarding of Democracy than we have made during the past three years. Wise and prudent men---intelligent conservatives---have long known that in a changing world worthy institutions can be conserved only by adjusting them to the changing time. In the words of the great essayist---'The voice of great events is proclaiming to us---Reform if you would preserve.' I am that kind of conservative because [I am that kind of liberal.](http://www.fdrlibrary.marist.edu/_resources/images/msf/msf00949)

Anyway it seems like some people need to hear this sort of thing. 