---
title: Oppenheimer and the horseshoe
author: Eric Rauchway
date: 2023-05-08
bibliography: ../../../common/war_nd.json
suppress-bibliography: true
csl: ../../../common/chicago-fullnote-bibliography-short-title-subsequent.csl
categories:
    - US strategy
    - Unconditional surrender
    - New Dealers at war
    - Historiography
---

The new trailer for Christopher Nolan's *Oppenheimer,* which press coverage says is based on the Kai Bird and Martin Sherwin biography *American Prometheus,* dropped today.

{{< video https://www.youtube.com/watch?v=uYPbbksJxIg >}}

I don't know anything about Nolan's movie other than what appears in the trailer, but I've seen enough Nolan to know that the politics in his movies can appear quite conservative. Conversely, I reviewed the Bird and Sherwin book when it came out, and I know it is not conservative. But if there's one area where the modern US right and left meet, it's on the subject of World War II. 

Indeed, one might without too much exaggeration say that the Cold War scholarly left largely adopted the wartime right's critique of the Roosevelt administration. To prove this statement fully would take more space than this post but I will cite in support of it the Cold War historian William Appleman Williams's [enthusiastic summary](https://www.nybooks.com/articles/1970/11/05/what-this-country-needs/) of Herbert Hoover's thinking: "So right it shakes you." I will also, even though it is not fully relevant here, provide Williams's description of Hoover's response to the Bonus Army, because it is hilarious:

> For the feel of how Hoover reacted, do not waste your time ransacking the archives. Just listen to The Doors doing the first verse of “The Soft Parade.”

Maybe quoting that is unfair to leftists who admire Hoover, but as I say, it is funny. Less funny is Williams's conviction that somehow Hoover opposed "the empire" and therefore was a sage we should heed.

Anyway, without (in this post) talking about whether I think the shared right/left critique of Roosevelt is correct, I just want to note that this sharing is real, and this similarity is most visible in an analysis of the war's end. As Marc Gallicchio's excellent 2020 book *Unconditional* makes clear, for the New Dealers, the war was an ideological war, and one that had to be pursued to the bitter end. Fascism had to be defeated utterly, in Japan as it was in Germany. "The supporters of unconditional surrender were mostly liberal Democrats, and the opponents were not," Gallicchio notes.[@gallicchioUnconditionalJapaneseSurrender2020, 209] 

By contrast, the American right wanted a swifter end to the war, which they had always thought was unnecessary, and merciful treatment of Japan so that it could serve as a bulwark against the Soviet Union. As Gallicchio points out, early critiques of the atomic bombings came from the political right, including from Hoover, from Douglas MacArthur, and from MacArthur aide and [actual wartime security risk](https://www.timesofisrael.com/new-book-deciphers-forgotten-intel-war-that-kept-the-nazis-from-the-holy-land/) as well as later John Birch member Bonner Fellers. Hoover and MacArthur agreed that an earlier peace would, in the general's words, "have avoided all our losses, the Atomic Bomb, and the entry of Russia into Manchuria." Hoover went further; "the whole Japanese war was a madman's desire to get into war." Gallicchio notes too that on the postwar right, "it became an article of faith" that MacArthur had, in January 1945, told Roosevelt the United States did not need the Soviets to help finish the war---a story that "was later publicly revealed to be a bald-faced lie."[@gallicchioUnconditionalJapaneseSurrender2020, 184--185]

Within a few years of the war, Republicans eager to blame Democrats for Mao's victory in China constructed a narrative in which the Roosevelt administration's unwillingness to accept peace overtures from Japan had led to Soviet entry into the war against Japan and thus the triumph of communism in Asia. Gallicchio notes that this narrative was "patently ridiculous," but it was widely accepted among "conspiratorially minded critics of Roosevelt."[@gallicchioUnconditionalJapaneseSurrender2020, 194]

Gallicchio goes on to note the appeal of this right-wing critique to the later left, citing Oliver Stone's deployment of Hoover and MacArthur to assert that the Japanese were ready to surrender long before the use of the atomic bombs. And he also notes that "invoking the opinions of the two Roosevelt haters contributes little to our understanding of Japan's willingness to surrender before August 1945." But it does highlight the continuity of right-wing and left-wing criticisms of US wartime policy.[@gallicchioUnconditionalJapaneseSurrender2020, 213]
