---
title: "No, Franklin Roosevelt was not a liberal proto-Trump; that's silly and I suspect you all know better"
draft: TRUE
categories:
  - New Deal
  - Historiography
  - Madness
---

On a trip to the National Archives recently we found a good document: it laid out the form and powers of a proposed Puerto Rico Company to implement the New Deal in Puerto Rico. This government corporation would buy and sell land and other property, and engage in all manner of other business; it was modeled expressly on the recently established Virgin Islands Company (VICO)---which promoted economic development in various ways, but chiefly bought sugarcane from local homesteaders, guaranteeing them a market, and processed some of it into rum for sale to mainland US consumers, thereby achieving full employment in the Virgin Islands in short order. The Puerto Rico Company was supposed to do likewise for the neighboring territory, only at about forty times the scale (inasmuch as Puerto Rico had about forty times as many people) and would therefore be funded by a richer source of revenue: VICO had a one-time appropriation from the Public Works Administration, but the Puerto Rico Company would get the revenue from the Agricultural Adjustment Administration program for sugar on the island. It was a tidy proposition, derived from a plan written by Carlos Chardón, the chancellor of the University of Puerto Rico, and backed by major political figures on the island---including Luis Muñoz Marín---and in Washington, including Rex Tugwell. 

It was good to find the document because we'd seen people mention it as a notion, but we hadn't seen anyone cite an explicit plan. But here it was---not, it's worth mentioning, in the folder it was supposed to be in, but in a neighboring one that we looked at just on the off-chance it might be there.

The reason it's hard to find is that the Puerto Rico Company never happened. Didn't get chartered, didn't get funded; didn't implement land redistribution and homesteading the way VICO did---didn't get an initialism the way other New Deal programs did. And it didn't happen because the Comptroller General killed it. 