---
title: "Full of, buckets of"
author: "Eric Rauchway"
date: "2025-09-04"
categories:
    - John Nance Garner
    - Language
---

As [recently as 2014,](https://www.google.com/books/edition/Days_of_Fire/eXCJDQAAQBAJ?hl=en&gbpv=1&dq=john+nance+garner+%22bucket+of+warm+spit%22&pg=PA60&printsec=frontcover) serious writers of nonfiction still considered it appropriate to coyly bowdlerize John Nance Garner's reported remark that the vice presidency was not worth a bucket of warm piss.[^1] (Garner, Roosevelt's vice president for his first two terms, was picked to assuage Texas and William Randolph Hearst in the nominating convention of 1932. Had Roosevelt been killed when he was shot at in February 1933, Garner would have become president. The New Deal would have looked a good deal different with the Texan who was (according to Hearst at least) an America Firster at the helm.)

I wonder what will become of the current vice president's [similarly excretory remark](https://nymag.com/intelligencer/article/rfk-jr-to-testify-before-senate-committee-live-updates.html#reaction-time) about the health and human services secretary's senatorial critics. Will the likes of Peter Baker (cited above) feel they must clean it up for publication? Or have we entered an era of greater authenticity in rendering vice presidential speech?

[^1]: Which he may actually have said, and [maybe even to Lyndon Johnson.](https://www.historynewsnetwork.org/article/not-worth-a-bucket-of-warm-spit)